server:
  port: 9090
spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: batch
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: ${DDL_METHOD_BATCH}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    open-in-view: false
  messages:
    encoding: UTF-8
    basename: messages
  sql:
    init:
      mode: ${SQL_MODE}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jwt:
    secret: ${JWT_SECRET}
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${SERVER_URL}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${SERVER_URL}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, profile_image
            client-authentication-method: client_secret_post
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${SERVER_URL}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
      revoke-url:
        naver: "https://nid.naver.com/oauth2.0/token"
        kakao: "https://kapi.kakao.com/v1/user/unlink"
        google: "https://accounts.google.com/o/oauth2/revoke"
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB
  batch:
    jdbc:
      initialize-schema: always
    # AWS S3
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2  # 버킷의 리전
    s3:
      bucket: badminton-team   # 버킷 이름
    stack:
      auto: false

custom:
  server:
    https: ${SERVER_URL}
    front: ${FRONT_URL}
    local: ${LOCAL_HOST}
    domain: ${DOMAIN}
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_NAME}
      password: ${MAIL_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
---
spring:
  config:
    activate:
      on-profile: develop
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG